name: Quack Patch

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: {}

permissions:
  contents: write
  pull-requests: write
  
jobs:
  blackduck:
    #runs-on: [self-hosted]
    runs-on: ubuntu-latest

    steps:
      ## Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

     ## Set up JDK 17 in runtime environment(WebGoat2023.3 requires Java17)
      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'
    
    ## Build
      ##- name: Build
       ## run: mvn compile
       # #mvn clean install
    
    ## Analyze with Black Duck        
      - name: Quack Patch
        continue-on-error: true
        shell: bash
        run: |
          bash <(curl -s -L https://detect.blackduck.com/detect11.sh) \
            --blackduck.offline.mode=false \
            --blackduck.url="${{ secrets.BLACKDUCK_URL }}" \
            --blackduck.trust.cert=true \
            --blackduck.api.token="${{ secrets.BLACKDUCK_API_TOKEN }}" \
            --detect.blackduck.scan.mode=RAPID \
            --detect.quack.patch.enabled=true \
            --detect.llm.api.endpoint="${{ secrets.LLM_API_ENDPOINT }}" \
            --detect.llm.api.key="${{ secrets.LLM_API_KEY }}" \
            --detect.llm.name=claude-sonnet-4-6 \
            --detect.quack.patch.output.path=quack-patch
            
      - name: Debug
        if: always()
        run: |
          ls -R /home/runner/blackduck/runs
      - name: Show Quack Patch Directory
        if: always()
        run: |
            find /home/runner/blackduck -name "*quack*" -print
            find /home/runner/blackduck -name "*.patch" -print
            find /home/runner/blackduck -name "*.diff" -print
            find /home/runner/blackduck -name "*.json" -print
      - name: Upload Quack Patch Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: quack-patch-results
          path: /home/runner/blackduck/runs/**/scan/quack-patch
          ##path: quack-patch
